import Provider from "./_components/Provider";
import Header from "./_components/Header";
import Main from "./_components/Main";
import Footer from "./_components/Footer";
import AuthProvider from "@/app/_lib/components/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <AuthProvider>
            <Header />
            <Main>{children}</Main>
            <Footer />
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
