import { NextPage, Metadata } from "next";
import { ReactNode } from "react";
import ChakraProviderWrapper from "@/lib/ChakraProviderWrapper";
import Header from "./_components/Header";
import Main from "./_components/Main";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    themeColor: "#ffffff",
}

interface Props {
    children: ReactNode
}

const RootLayout: NextPage<Props> = ({ children }) => {
    return (
        <html lang="ja">
            <head />

            <body>
                <ChakraProviderWrapper>
                    <Header />

                    <Main>
                        {children}
                    </Main>

                    <Footer />
                </ChakraProviderWrapper>
            </body>
        </html>
    )
}

export default RootLayout
