import { NextPage, Metadata } from "next";
import Link from "next/link";
import { ReactNode } from "react";

// const inter = Inter({ subsets: ['latin'] })

// exportしたらheadに自動的に追加される
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    themeColor: "#ffffff",
}

interface Props {
    children: ReactNode
}

// _app.tsx, _document.tsxがなくなったぽいので、html,bodyはここで書く
const RootLayout: NextPage<Props> = ({ children }) => {
    return (
        <html lang="ja">
            <head />
            <body>
                <header>
                    <h1>
                        <Link href="/">ブログ</Link>
                    </h1>
                    <Link href="/articles/new">記事を書く</Link>
                </header>

                <main>
                    {children}
                </main>

                <footer>
                    <small>© 2023 azukiazusa</small>
                </footer>
            </body>
        </html>
    )
}

export default RootLayout
