name: "学習予定"
description: "今週の学習内容"
title: "【名前・今日の日付・期限】～内容～ "
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 内容
      description: 今回学習する内容
      value: "- [ ] 学習内容１"
    validations:
      required: true
  - type: dropdown
    id: fb_assignee
    attributes:
      label: FB担当者
      options:
        - エネス
        - 英太郎
        - まだ不明
    validations:
      required: true
  - type: checkboxes
    id: affirmed
    attributes:
      label: 内容設計の現況
      options:
        - label: 内容書き込み済み（＝WIPじゃない）
        - label: FB者が内容に承諾済み
