name: "学習予定"
description: "今週の学習内容"
title: "【名前・今日の日付・期限】～内容～ "
assignees:
  - enes1004
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 内容
      description: 今回学習する内容
      value: "- [] 学習内容１"
    validations:
      required: true
  - type: checkboxes
    id: affirmed
    attributes:
      label: 内容設計の現況
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: 内容書き込み済み（＝WIPじゃない）
        - label: FB者が内容承諾済み
